# Generated by Django 5.2.1 on 2025-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_reporting_days',
            field=models.IntegerField(blank=True, default=7, help_text='Number of days for custom reporting frequency', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Every 1 day'), ('3days', 'Every 3 days'), ('weekly', 'Once a week'), ('monthly', 'Once a month'), ('custom', 'Custom')], default='weekly', max_length=10),
        ),
    ]
